# Generated by Django 6.0.4 on 2026-05-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_angkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.IntegerField(default=2020),
        ),
    ]
